import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Scheduler from "@/components/Scheduler";
import SyncGate from "@/components/SyncGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allowed = new Set(["en", "uk", "pl", "de", "es", "fr", "it", "pt"]);
  const cookieLocale = (await cookies()).get("locale")?.value || "uk";
  const htmlLang = allowed.has(cookieLocale) ? cookieLocale : "uk";
  return (
    <html lang={htmlLang}>
      <head>
        <meta charSet="utf-8" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <a href="#main" className="skip-link">Skip to content</a>
        <SyncGate />
        <Scheduler />
        <Navbar />
        <main id="main" className="mx-auto max-w-6xl px-6 py-8">{children}</main>
      </body>
    </html>
  );
}
